version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_practice
    platform: linux/arm64
    ports:
      - "7474:7474" # HTTP 브라우저 포트
      - "7687:7687" # Bolt 프로토콜 포트 (드라이버 연결용)
    environment:
      - NEO4J_AUTH=neo4j/testpassword
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - ACTIVE_DATASET=${ACTIVE_DATASET}
    volumes:
      - ./neo4j/data/${ACTIVE_DATASET}:/data
      - ./neo4j/logs/${ACTIVE_DATASET}:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      - ./dataset:/dataset:ro
      - ./neo4j_init.sh:/neo4j_init.sh:ro
    entrypoint: /neo4j_init.sh
    restart: unless-stopped
