# https://taskfile.dev

version: "3"

dotenv: [".env.task"]

tasks:
  build:
    cmds:
      - go build -C cmd/neo4j-mcp -o ../../bin/ {{.CLI_ARGS}}
  run:
    cmds:
      - go run ./cmd/neo4j-mcp
  run:compiled:
    cmds:
      - ./bin/neo4j-mcp {{.CLI_ARGS}}
  generate:
    cmds:
      - go generate ./...
  # pass CLI args as task:test -- -v
  test:
    cmds:
      - go test ./... {{.CLI_ARGS}}
  test:unit:
    cmds:
      - go test ./internal/... {{.CLI_ARGS}}
  test:int:
    cmds:
      - go test -tags=integration ./test/integration/... {{.CLI_ARGS}}
  test:e2e:
    cmds:
      - go test -tags=e2e ./test/e2e/... {{.CLI_ARGS}}
  test:clean:
    cmds:
      - go clean -testcache
  lint:
    cmds:
      - golangci-lint run
  inspect:
    cmds:
      - npx @modelcontextprotocol/inspector go run ./cmd/neo4j-mcp
  interactive-client:
    cmds:
      - go run ./client/... bin/neo4j-mcp
