// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/neo4j/mcp/internal/analytics (interfaces: Service,HTTPClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_analytics.go -package=analytics_mocks -typed github.com/neo4j/mcp/internal/analytics Service,HTTPClient
//

// Package analytics_mocks is a generated GoMock package.
package analytics_mocks

import (
	io "io"
	http "net/http"
	reflect "reflect"

	analytics "github.com/neo4j/mcp/internal/analytics"
	config "github.com/neo4j/mcp/internal/config"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Disable mocks base method.
func (m *MockService) Disable() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Disable")
}

// Disable indicates an expected call of Disable.
func (mr *MockServiceMockRecorder) Disable() *MockServiceDisableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockService)(nil).Disable))
	return &MockServiceDisableCall{Call: call}
}

// MockServiceDisableCall wrap *gomock.Call
type MockServiceDisableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDisableCall) Return() *MockServiceDisableCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDisableCall) Do(f func()) *MockServiceDisableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDisableCall) DoAndReturn(f func()) *MockServiceDisableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EmitEvent mocks base method.
func (m *MockService) EmitEvent(event analytics.TrackEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EmitEvent", event)
}

// EmitEvent indicates an expected call of EmitEvent.
func (mr *MockServiceMockRecorder) EmitEvent(event any) *MockServiceEmitEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmitEvent", reflect.TypeOf((*MockService)(nil).EmitEvent), event)
	return &MockServiceEmitEventCall{Call: call}
}

// MockServiceEmitEventCall wrap *gomock.Call
type MockServiceEmitEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceEmitEventCall) Return() *MockServiceEmitEventCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceEmitEventCall) Do(f func(analytics.TrackEvent)) *MockServiceEmitEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceEmitEventCall) DoAndReturn(f func(analytics.TrackEvent)) *MockServiceEmitEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Enable mocks base method.
func (m *MockService) Enable() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Enable")
}

// Enable indicates an expected call of Enable.
func (mr *MockServiceMockRecorder) Enable() *MockServiceEnableCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockService)(nil).Enable))
	return &MockServiceEnableCall{Call: call}
}

// MockServiceEnableCall wrap *gomock.Call
type MockServiceEnableCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceEnableCall) Return() *MockServiceEnableCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceEnableCall) Do(f func()) *MockServiceEnableCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceEnableCall) DoAndReturn(f func()) *MockServiceEnableCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsEnabled mocks base method.
func (m *MockService) IsEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEnabled indicates an expected call of IsEnabled.
func (mr *MockServiceMockRecorder) IsEnabled() *MockServiceIsEnabledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEnabled", reflect.TypeOf((*MockService)(nil).IsEnabled))
	return &MockServiceIsEnabledCall{Call: call}
}

// MockServiceIsEnabledCall wrap *gomock.Call
type MockServiceIsEnabledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceIsEnabledCall) Return(arg0 bool) *MockServiceIsEnabledCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceIsEnabledCall) Do(f func() bool) *MockServiceIsEnabledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceIsEnabledCall) DoAndReturn(f func() bool) *MockServiceIsEnabledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewConnectionInitializedEvent mocks base method.
func (m *MockService) NewConnectionInitializedEvent(connInfo analytics.ConnectionEventInfo) analytics.TrackEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConnectionInitializedEvent", connInfo)
	ret0, _ := ret[0].(analytics.TrackEvent)
	return ret0
}

// NewConnectionInitializedEvent indicates an expected call of NewConnectionInitializedEvent.
func (mr *MockServiceMockRecorder) NewConnectionInitializedEvent(connInfo any) *MockServiceNewConnectionInitializedEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConnectionInitializedEvent", reflect.TypeOf((*MockService)(nil).NewConnectionInitializedEvent), connInfo)
	return &MockServiceNewConnectionInitializedEventCall{Call: call}
}

// MockServiceNewConnectionInitializedEventCall wrap *gomock.Call
type MockServiceNewConnectionInitializedEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceNewConnectionInitializedEventCall) Return(arg0 analytics.TrackEvent) *MockServiceNewConnectionInitializedEventCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceNewConnectionInitializedEventCall) Do(f func(analytics.ConnectionEventInfo) analytics.TrackEvent) *MockServiceNewConnectionInitializedEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceNewConnectionInitializedEventCall) DoAndReturn(f func(analytics.ConnectionEventInfo) analytics.TrackEvent) *MockServiceNewConnectionInitializedEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewGDSProjCreatedEvent mocks base method.
func (m *MockService) NewGDSProjCreatedEvent() analytics.TrackEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGDSProjCreatedEvent")
	ret0, _ := ret[0].(analytics.TrackEvent)
	return ret0
}

// NewGDSProjCreatedEvent indicates an expected call of NewGDSProjCreatedEvent.
func (mr *MockServiceMockRecorder) NewGDSProjCreatedEvent() *MockServiceNewGDSProjCreatedEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGDSProjCreatedEvent", reflect.TypeOf((*MockService)(nil).NewGDSProjCreatedEvent))
	return &MockServiceNewGDSProjCreatedEventCall{Call: call}
}

// MockServiceNewGDSProjCreatedEventCall wrap *gomock.Call
type MockServiceNewGDSProjCreatedEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceNewGDSProjCreatedEventCall) Return(arg0 analytics.TrackEvent) *MockServiceNewGDSProjCreatedEventCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceNewGDSProjCreatedEventCall) Do(f func() analytics.TrackEvent) *MockServiceNewGDSProjCreatedEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceNewGDSProjCreatedEventCall) DoAndReturn(f func() analytics.TrackEvent) *MockServiceNewGDSProjCreatedEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewGDSProjDropEvent mocks base method.
func (m *MockService) NewGDSProjDropEvent() analytics.TrackEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewGDSProjDropEvent")
	ret0, _ := ret[0].(analytics.TrackEvent)
	return ret0
}

// NewGDSProjDropEvent indicates an expected call of NewGDSProjDropEvent.
func (mr *MockServiceMockRecorder) NewGDSProjDropEvent() *MockServiceNewGDSProjDropEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewGDSProjDropEvent", reflect.TypeOf((*MockService)(nil).NewGDSProjDropEvent))
	return &MockServiceNewGDSProjDropEventCall{Call: call}
}

// MockServiceNewGDSProjDropEventCall wrap *gomock.Call
type MockServiceNewGDSProjDropEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceNewGDSProjDropEventCall) Return(arg0 analytics.TrackEvent) *MockServiceNewGDSProjDropEventCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceNewGDSProjDropEventCall) Do(f func() analytics.TrackEvent) *MockServiceNewGDSProjDropEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceNewGDSProjDropEventCall) DoAndReturn(f func() analytics.TrackEvent) *MockServiceNewGDSProjDropEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewStartupEvent mocks base method.
func (m *MockService) NewStartupEvent(transportMode config.TransportMode, tlsEnabled bool, mcpServer string) analytics.TrackEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewStartupEvent", transportMode, tlsEnabled, mcpServer)
	ret0, _ := ret[0].(analytics.TrackEvent)
	return ret0
}

// NewStartupEvent indicates an expected call of NewStartupEvent.
func (mr *MockServiceMockRecorder) NewStartupEvent(transportMode, tlsEnabled, mcpServer any) *MockServiceNewStartupEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStartupEvent", reflect.TypeOf((*MockService)(nil).NewStartupEvent), transportMode, tlsEnabled, mcpServer)
	return &MockServiceNewStartupEventCall{Call: call}
}

// MockServiceNewStartupEventCall wrap *gomock.Call
type MockServiceNewStartupEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceNewStartupEventCall) Return(arg0 analytics.TrackEvent) *MockServiceNewStartupEventCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceNewStartupEventCall) Do(f func(config.TransportMode, bool, string) analytics.TrackEvent) *MockServiceNewStartupEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceNewStartupEventCall) DoAndReturn(f func(config.TransportMode, bool, string) analytics.TrackEvent) *MockServiceNewStartupEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NewToolEvent mocks base method.
func (m *MockService) NewToolEvent(toolsUsed string, success bool) analytics.TrackEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewToolEvent", toolsUsed, success)
	ret0, _ := ret[0].(analytics.TrackEvent)
	return ret0
}

// NewToolEvent indicates an expected call of NewToolEvent.
func (mr *MockServiceMockRecorder) NewToolEvent(toolsUsed, success any) *MockServiceNewToolEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewToolEvent", reflect.TypeOf((*MockService)(nil).NewToolEvent), toolsUsed, success)
	return &MockServiceNewToolEventCall{Call: call}
}

// MockServiceNewToolEventCall wrap *gomock.Call
type MockServiceNewToolEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceNewToolEventCall) Return(arg0 analytics.TrackEvent) *MockServiceNewToolEventCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceNewToolEventCall) Do(f func(string, bool) analytics.TrackEvent) *MockServiceNewToolEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceNewToolEventCall) DoAndReturn(f func(string, bool) analytics.TrackEvent) *MockServiceNewToolEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
	isgomock struct{}
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Post mocks base method.
func (m *MockHTTPClient) Post(url, contentType string, body io.Reader) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", url, contentType, body)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockHTTPClientMockRecorder) Post(url, contentType, body any) *MockHTTPClientPostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockHTTPClient)(nil).Post), url, contentType, body)
	return &MockHTTPClientPostCall{Call: call}
}

// MockHTTPClientPostCall wrap *gomock.Call
type MockHTTPClientPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHTTPClientPostCall) Return(arg0 *http.Response, arg1 error) *MockHTTPClientPostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHTTPClientPostCall) Do(f func(string, string, io.Reader) (*http.Response, error)) *MockHTTPClientPostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHTTPClientPostCall) DoAndReturn(f func(string, string, io.Reader) (*http.Response, error)) *MockHTTPClientPostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
