version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_ch2
    platform: linux/arm64
    ports:
      - "7474:7474" # HTTP 브라우저
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - ACTIVE_DATASET=${ACTIVE_DATASET}
    volumes:
      - neo4j_data_ch2:/data
      - neo4j_logs_ch2:/logs
      - ../../neo4j/import:/var/lib/neo4j/import
      - ../../neo4j/plugins:/plugins
      - ../../dataset:/dataset:ro
      - ./neo4j_init.sh:/neo4j_init.sh:ro
    entrypoint: /neo4j_init.sh
    restart: unless-stopped

volumes:
  neo4j_data_ch2:
  neo4j_logs_ch2:
